upstream django {
    server recon_tools:8001; 
}

server {
    listen      8000;
    server_name tools.doscom.org;
    charset     utf-8;

    client_max_body_size 75M;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://django;
    }
}
